version: 0.3.9

datasets_dir: resources/datasets #without trailing slash !

datasets: ../../all_datasets.csv
ssh_servers: ../../ssh_servers.csv

dorado_version: 0.6.1-linux-x64
guppy_version: 6.3.2_linux64

contig_coverages: [1, 5, 10, 20, 30, 40, 50]

modkit_filter_threshold: 0.66

dorado_batchsize: 512

threads: 12
threads_nanodisco: 4

timeout: '2h'
retries: 1

backup_alias: backup
backup_dir: /vol/data/

tombo_per_read_stats: false

models:
    'r10.4.1':
        5000:
            simplex: dna_r10.4.1_e8.2_400bps_sup@v4.3.0
            modifications: 
                - res_dna_r10.4.1_e8.2_400bps_sup@v4.3.0_4mC_5mC@v1
                - dna_r10.4.1_e8.2_400bps_sup@v4.3.0_6mA@v2
        4000:
            simplex: res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1
            modifications:
                - res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1_5mC@v2
                - res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1_6mA@v2
    'r9.4.1': # simplex is automatically determined
        modifications: res_dna_r941_min_modbases-all-context_v001